### PR TITLE
Bump pdfjs-dist to 2.5.207

### PR DESCRIPTION
**Pull request by ryan-miller-highspot**
Bumps `pdfjs-dist` to the latest version (2.5.207), which addresses at least one rendering bug for us internally at Highspot. Thanks for supporting this library @robrez!

### CODE REVIEW

**Comment by robrez** [comment]
Thanks for the help, I'll look at getting this merged ASAP

**Comment by ryan-miller-highspot** [comment]
Thanks @robrez!

**Comment by robrez** [comment]
Created an rc https://github.com/bundled-es-modules/pdfjs-dist/tree/feature/v2.5.207-rc

```
$ npm i @bundled-es-modules/pdfjs-dist@2.5.207-rc1
```

Give this a try, and let me know if it seems to be working okay for you... I may do a bit of testing in one of my packages that depends on this as well.  If everything seems good, we'll publish `v2.5.207`

**Comment by ryan-miller-highspot** [comment]
Sounds great–we'll give it a shot and report back!

**Pull request merged**
